# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - workouttracker-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: |
          dotnet build --configuration Release

      - name: Publish Web Project
        run: |
          dotnet publish WorkoutTracker.Web/WorkoutTracker.Web.csproj -c Release -o "${{env.DOTNET_ROOT}}/web" --no-build
          # Rename appsettings.json to avoid conflicts
          mv "${{env.DOTNET_ROOT}}/web/appsettings.json" "${{env.DOTNET_ROOT}}/web/appsettings.web.json"

      - name: Publish API Project
        run: |
          dotnet publish WorkoutTracker.API/WorkoutTracker.API.csproj -c Release -o "${{env.DOTNET_ROOT}}/api" --no-build
          # Rename appsettings.json to avoid conflicts
          mv "${{env.DOTNET_ROOT}}/api/appsettings.json" "${{env.DOTNET_ROOT}}/api/appsettings.api.json"

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: ${{env.DOTNET_ROOT}}/web

      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: ${{env.DOTNET_ROOT}}/api

  deploy-web:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download Web artifact
        uses: actions/download-artifact@v4
        with:
          name: web-app
      
      - name: Rename appsettings for Web
        run: |
          mv appsettings.web.json appsettings.json
      
      - name: Deploy Web to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'workouttracker-web'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BE636FD521A845AA975E2204D82EB1ED }}

  deploy-api:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-api.outputs.webapp-url }}
    
    steps:
      - name: Download API artifact
        uses: actions/download-artifact@v4
        with:
          name: api-app
      
      - name: Rename appsettings for API
        run: |
          mv appsettings.api.json appsettings.json
      
      - name: Deploy API to Azure Web App
        id: deploy-to-api
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'workouttracker-api'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_API }}