name: Build and deploy ASP.Net Core app to Azure Web App - WorkoutTracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build Web Project
        run: |
          dotnet build WorkoutTracker.Web/WorkoutTracker.Web.csproj --configuration Release

      - name: Build API Project
        run: |
          dotnet build WorkoutTracker.API/WorkoutTracker.API.csproj --configuration Release

      - name: Publish Web Project
        run: |
          dotnet publish WorkoutTracker.Web/WorkoutTracker.Web.csproj -c Release -o "${{env.DOTNET_ROOT}}/publish/web" --no-build
          # Rename appsettings.json to avoid conflicts
          if [ -f "${{env.DOTNET_ROOT}}/publish/web/appsettings.json" ]; then
            mv "${{env.DOTNET_ROOT}}/publish/web/appsettings.json" "${{env.DOTNET_ROOT}}/publish/web/appsettings.web.json"
          fi

      - name: Publish API Project
        run: |
          dotnet publish WorkoutTracker.API/WorkoutTracker.API.csproj -c Release -o "${{env.DOTNET_ROOT}}/publish/api" --no-build
          # Rename appsettings.json to avoid conflicts
          if [ -f "${{env.DOTNET_ROOT}}/publish/api/appsettings.json" ]; then
            mv "${{env.DOTNET_ROOT}}/publish/api/appsettings.json" "${{env.DOTNET_ROOT}}/publish/api/appsettings.api.json"
          fi

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: ${{env.DOTNET_ROOT}}/publish/web

      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: ${{env.DOTNET_ROOT}}/publish/api

  deploy-web:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download Web artifact
        uses: actions/download-artifact@v4
        with:
          name: web-app
      
      - name: Rename appsettings for Web
        run: |
          if [ -f "appsettings.web.json" ]; then
            mv appsettings.web.json appsettings.json
          fi
      
      - name: Deploy Web to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'workouttracker-web'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BE636FD521A845AA975E2204D82EB1ED }}

  deploy-api:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-api.outputs.webapp-url }}
    
    steps:
      - name: Download API artifact
        uses: actions/download-artifact@v4
        with:
          name: api-app
      
      - name: Rename appsettings for API
        run: |
          if [ -f "appsettings.api.json" ]; then
            mv appsettings.api.json appsettings.json
          fi
      
      - name: Deploy API to Azure Web App
        id: deploy-to-api
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'workouttracker-api'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BE636FD521A845AA975E2204D82EB1ED }} 