name: Build and deploy ASP.Net Core app to Azure Web App - WorkoutTracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME_WEB: 'workouttracker-web'
  AZURE_WEBAPP_NAME_API: 'workouttracker-api'
  AZURE_WEBAPP_PACKAGE_PATH_WEB: '${{env.DOTNET_ROOT}}/publish/web'
  AZURE_WEBAPP_PACKAGE_PATH_API: '${{env.DOTNET_ROOT}}/publish/api'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Rename appsettings files before build
        run: |
          if (Test-Path "WorkoutTracker.Web/appsettings.json") {
            Rename-Item -Path "WorkoutTracker.Web/appsettings.json" -NewName "appsettings.web.json"
          }
          if (Test-Path "WorkoutTracker.API/appsettings.json") {
            Rename-Item -Path "WorkoutTracker.API/appsettings.json" -NewName "appsettings.api.json"
          }

      - name: Build Web Project
        run: |
          dotnet build WorkoutTracker.Web/WorkoutTracker.Web.csproj --configuration Release

      - name: Build API Project
        run: |
          dotnet build WorkoutTracker.API/WorkoutTracker.API.csproj --configuration Release

      - name: Publish Web Project
        run: |
          dotnet publish WorkoutTracker.Web/WorkoutTracker.Web.csproj -c Release -o "${{env.DOTNET_ROOT}}/publish/web" --no-build
          if (Test-Path "${{env.DOTNET_ROOT}}/publish/web/appsettings.web.json") {
            Rename-Item -Path "${{env.DOTNET_ROOT}}/publish/web/appsettings.web.json" -NewName "appsettings.json"
          }

      - name: Publish API Project
        run: |
          dotnet publish WorkoutTracker.API/WorkoutTracker.API.csproj -c Release -o "${{env.DOTNET_ROOT}}/publish/api" --no-build
          if (Test-Path "${{env.DOTNET_ROOT}}/publish/api/appsettings.api.json") {
            Rename-Item -Path "${{env.DOTNET_ROOT}}/publish/api/appsettings.api.json" -NewName "appsettings.json"
          }

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: ${{env.DOTNET_ROOT}}/publish/web

      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: ${{env.DOTNET_ROOT}}/publish/api

  deploy-web:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download Web artifact
        uses: actions/download-artifact@v4
        with:
          name: web-app

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Web to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_WEB }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH_WEB }}

  deploy-api:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-api.outputs.webapp-url }}
    
    steps:
      - name: Download API artifact
        uses: actions/download-artifact@v4
        with:
          name: api-app

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy API to Azure Web App
        id: deploy-to-api
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_API }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH_API }} 